
ci:
  autofix_prs: true
  autoupdate_schedule: weekly
  autofix_commit_msg: "fix(pre_commit): 🎨 auto format pre-commit hooks"
  autoupdate_commit_msg: "chore(pre_commit): ⬆ pre_commit autoupdate"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
        exclude: mkdocs.yml
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
      - id: detect-private-key
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys', '--indent=4']
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.18
    hooks:
    - id: mdformat
      additional_dependencies:
      - mdformat-admon
      - mdformat-mkdocs[recommended]
